### ISSUE TITLE
依赖版本和构建过程的安装问题

### ISSUE THREAD

**Issue by xwxYa** [pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch#1]
当尝试在我的环境中安装 LiteLoaderQQNT-NekoImageGallerySearch 时，我遇到了一些依赖版本和构建过程中的问题。具体来说，有一些包的版本问题以及构建过程中的等待状态。

**步骤重现**
克隆仓库到本地。
运行 npm install -g yarn，yarn plugin-build和yarn install。
当运行yarn install时，遇到无法找到某些依赖的指定版本，例如 @rollup/rollup-android-arm-eabi 要求的 4.15.0 版本不存在，需要从列表中选择其他版本。
选择 4.14.3 版本后，出现了对 vite-plugin-cp 和 vite-plugin-singlefile 的警告，表明存在未满足的同伴依赖。
在安装过程中，多个 electron 包一直处于等待状态。

环境信息
操作系统：Windows 11
Node.js版本：v20.12.2
Yarn版本：1.22.22

尝试过的解决办法
更新 Node.js 和 Yarn 到最新版本。
尝试清除 Yarn 缓存。
检查网络连接。

希望得到你的帮助，感谢！

**Comment by pk5ls20** [comment]
未能复现。
把本插件文件夹删掉，重新构建试试？
