### ISSUE TITLE
[Bug]:最新版右键图像选择相似搜索上方图片不改变

### ISSUE THREAD

**Issue by Shapaper233** [pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch#16]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/157946924/1eb02cd7-9284-4467-b65e-c3c5e5ed38f6)
最新版在下方右键图像选择相似搜索上方图片不改变
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/157946924/83ee4ab6-8c2a-4ba4-97fe-1021a9824136)

**Comment by Shapaper233** [comment]
并且在其他界面搜索相似图不会自动切换到图搜图

**Comment by pk5ls20** [comment]
当时写的时候没有考虑到这一点，稍晚点添加下这部分逻辑（

**Comment by Shapaper233** [comment]
大佬这个似乎还没修😚

> 并且在其他界面搜索相似图不会自动切换到图搜图

**Comment by pk5ls20** [comment]
> 大佬这个似乎还没修😚
> 
> > 并且在其他界面搜索相似图不会自动切换到图搜图

我感觉不切换到图搜图比较好😂
嘶，但是感觉切换到图搜图也有道理（
看看后续可不可以作为一个可选选项
