### ISSUE TITLE
[BUG]：与transitio冲突

### ISSUE THREAD

**Issue by Shapaper233** [pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch#18]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/157946924/67648637-d69d-4d9b-bb38-26668159bfe6)
我发现只要安装了这个插件，就会导致transitio的列表为空白。
因为个人测试transitio没和其他插件冲突，所以怀疑可能是该插件的BUG。
之前是可以正常使用的，似乎是最新几个版本的问题，我去测试下

**Comment by pk5ls20** [comment]
我稍晚点发下版吧😂
