### ISSUE TITLE
构建报错

### ISSUE THREAD

**Issue by gy2360688045** [pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch#2]
运行会返回未找到package.json，以下是运行日志，LiteLoaderQQNT和node安装位置都在D，不知道是不是安装位置的问题
C:\Users\23606>yarn install && yarn plugin-build
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.07s.
yarn run v1.22.22
error Couldn't find a package.json file in "C:\\Users\\23606"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by pk5ls20** [comment]
> 运行会返回未找到package.json，以下是运行日志，LiteLoaderQQNT和node安装位置都在D，不知道是不是安装位置的问题 C:\Users\23606>yarn install && yarn plugin-build yarn install v1.22.22 [1/4] Resolving packages... success Already up-to-date. Done in 0.07s. yarn run v1.22.22 error Couldn't find a package.json file in "C:\Users\23606" info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

cd 到**插件目录**后再执行yarn install 和 yarn plugin-build
