### ISSUE TITLE
运行yarn install && yarn plugin-build报not found

### ISSUE THREAD

**Issue by gy2360688045** [pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch#3]
日志
D:\QQ\resources\app\LiteLoaderQQNT\plugins>yarn install && yarn plugin-build
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.10s.
yarn run v1.22.22
error Command "plugin-build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by pk5ls20** [comment]
请在**插件目录下**执行yarn install 和 yarn plugin-build
显然你现在所在的目录不是本插件所在目录
