### ISSUE TITLE
没有数据

### ISSUE THREAD

**Issue by jayce2048** [pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch#4]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/f370b51a-25eb-4a5e-a651-159aab70489b)
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/a1b56132-ef72-4a4a-ae11-d613f978779f)
虽然说运行起来了，接口也能调通，但是并没有内容，是需要再下载个什么model吗还是？

**Comment by jayce2048** [comment]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/923b046e-8371-4dc2-b261-04143b100d26)
大佬，按照你说的方式，会出现这个错误

**Comment by pk5ls20** [comment]
> ![image](https://private-user-images.githubusercontent.com/169036891/328410004-872ef6bd-78a7-42aa-a0d4-2bad2f03ed99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjU5NDQsIm5iZiI6MTcxNTA2NTY0NCwicGF0aCI6Ii8xNjkwMzY4OTEvMzI4NDEwMDA0LTg3MmVmNmJkLTc4YTctNDJhYS1hMGQ0LTJiYWQyZjAzZWQ5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwNzA3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzhkZTdlZTUxNzdhMDAzZmZjNWEyYjE0NmE2NTI5ZGZhNWJhM2UxYTU5ZGQ2MDFkYThlODNlZjIwZjYyMzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sh8OtBMhdDaJKQ-JgO9naYdCwNAPexFK6bh4qi7p9aA) 大佬，为什么在QQ里面是没有显示的

- 检查一下主项目 NekoImageGallery 中的文件服务部分设置，确保索引时使用的文件服务和开启服务器后使用的文件服务一致

**Comment by jayce2048** [comment]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/2b77b3b3-e482-410e-a9fc-0dc98dea3e29)
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/7968596e-6f3e-4587-9808-9b9819c680e3)
第一张图是NekoImageGallerySearch-app,也就是网页版的，正常显示

**Comment by pk5ls20** [comment]
> ![image](https://private-user-images.githubusercontent.com/169036891/328465879-2b77b3b3-e482-410e-a9fc-0dc98dea3e29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzc1MDAsIm5iZiI6MTcxNTA3NzIwMCwicGF0aCI6Ii8xNjkwMzY4OTEvMzI4NDY1ODc5LTJiNzdiM2IzLWU0ODItNDEwZS1hOWZjLTBkYzk4ZGVhM2UyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxMDIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2QxNDlhNDE5ODczNzEyY2RjZWM4N2MwMTlkZTM5ODg4YjVkZDczNmU3YmI1MTcxNDYyZWJmNTI0NzYyMjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RpVcMlceWcb_cByV9EJ92ocLbhWBT32pViHr5XN_N1g) ![image](https://private-user-images.githubusercontent.com/169036891/328466107-7968596e-6f3e-4587-9808-9b9819c680e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzc1MDAsIm5iZiI6MTcxNTA3NzIwMCwicGF0aCI6Ii8xNjkwMzY4OTEvMzI4NDY2MTA3LTc5Njg1OTZlLTZmM2UtNDU4Ny05ODA4LTliOTgxOWM2ODBlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxMDIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWFmY2M2YjYxN2QyNWFjNzM0NGM2YjQxMmViNGQ3YzgwYTRkMmUxMDNlZWNlOTkxOWY2MzdmZWM2ZTRiN2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xqVJoIKDcWpRPsvl44YOLm5ZS3bV4Nw52PYsUZiEW4Q) 第一张图是NekoImageGallerySearch-app,也就是网页版的，正常显示 第二张图是QQ的，不正常显示 文件服务应该是正常配置的

试试仅使用本项目的WebUI部分，看看能不能正常显示图片
1. git clone 本项目
2. 在项目路径下：
```
npm install -g yarn
yarn install 
```
3. 设置以下环境变量（e.g powershell下）：
```
$Env:VITE_LLNT_NEKOIMAGE_DEV = "1"
$Env:VITE_LLNT_NEKOIMAGE_DEV__ACCESS_TOKEN = "YOUR-ADDRESS-TOKEN"
$Env:VITE_LLNT_NEKOIMAGE_DEV__NEKOIMAGE_API = "YOUR-API-ENDPOINT"
```
4. 在项目路径下：
```
yarn ui-dev
```

**Comment by jayce2048** [comment]
按照你的方法，仅使用本项目的WebUI部分，可以正常显示图片，但是这个QQ里面不知道为什么不行...
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/237cf478-c1bf-4e0a-9124-e407cc6ea401)
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/cce43bf6-32a6-497d-93f4-70b394ca0606)
这里设置的这部分都是一样的

**Comment by pk5ls20** [comment]
仍无法复现...
1. 提供下你的操作系统型号，QQ版本号和LiteloaderQQNT版本号
2. **下载最新构建版后**，尝试在QQ可执行文件目录内从终端启动QQ：`./qq.exe --enable-logging` ，然后在QQ内完成一次搜索操作，最后将终端输出部分上传

**Comment by jayce2048** [comment]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/849d2405-bd29-4055-89be-678f6f634aa8)
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/dbd00d3d-ec7f-4618-8ce1-4e8406606058)
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/59724041-8748-4279-9454-ce6d76964f71)
现在是这么个情况了

**Comment by jayce2048** [comment]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/c947e92d-4862-4004-aa31-130dbe7ee58a)
可以了，我更新了LiteLoaderQQNT到最新版本后，正常了，感谢！

**Comment by jayce2048** [comment]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/169036891/949011cb-9640-45f5-a45f-2cbe2e647460)
已经可以正常使用了，LiteLoaderQQNT我更新到最新版本后就有用了，感谢！
