### ISSUE TITLE
支持图片上传

### ISSUE THREAD

**Issue by Shapaper233** [pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch#5]
看上游支持上传图片了，能支持一下吗？
比如右键表情上传

**Comment by pk5ls20** [comment]
> 看上游支持上传图片了，能支持一下吗？
> 比如右键表情上传

最近比较忙，会找时间写的，也欢迎来PR

**Comment by pk5ls20** [comment]
https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/commit/e8ebe19b250cc0d796eba13ecb0158c55f31d4f3

**Comment by Shapaper233** [comment]
版本号似乎忘记更新了（
是不是代表测试可用就可以发布release了😁

**Comment by Shapaper233** [comment]
请问支持右键图片直接上传嘛，个人理解是不是可以复用那个右键的逻辑，按下后直接丢上传列表并弹个气泡提示，表明正在上传😚

**Comment by pk5ls20** [comment]
> 版本号似乎忘记更新了（ 是不是代表测试可用就可以发布release了😁

稍晚点更新版本号，因为还没写完（）

**Comment by pk5ls20** [comment]
> 请问支持右键图片直接上传嘛

会支持的，稍晚点写

> 个人理解是不是可以复用那个右键的逻辑，按下后直接丢上传列表并弹个气泡提示，表明正在上传😚

差不多

**Comment by Shapaper233** [comment]
嗯嗯

目前这个版本，我这边测试上传无法正常用qwq
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/157946924/1cd113dd-c4a3-47e0-bae9-e518cb4dbda5)
是已完成功能的bug还是未实装啊😭

**Comment by pk5ls20** [comment]
> 嗯嗯
> 
> 目前这个版本，我这边测试上传无法正常用qwq ![image](https://private-user-images.githubusercontent.com/157946924/344382388-1cd113dd-c4a3-47e0-bae9-e518cb4dbda5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTQwMjUsIm5iZiI6MTcxOTY1MzcyNSwicGF0aCI6Ii8xNTc5NDY5MjQvMzQ0MzgyMzg4LTFjZDExM2RkLWM0YTMtNDdlMC1iYWU5LWU1MThjYjRkYmRhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwOTM1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTVlOGM3OWJiMmY5M2IwZmU5Yzk2YjY2ZTgyMDQ2ODU4YjI2ZDA3YzJhZGFlMTlkZjMyZTBlNmEyMjRhMTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i-QaMgmRmKhCDqfK6UNL5beDKZqXQ5Au0m92yqmI52s) 是已完成功能的bug还是未实装啊😭


看下是否配置API Admin Token以及配置是否生效，正常应该这样（注意划线部分）：

<img width="513" alt="image" src="https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/114645197/4693b1a0-29f9-4853-9910-027828fd92c5">


https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/commit/e8ebe19b250cc0d796eba13ecb0158c55f31d4f3 直接上传倒是写好了，我这边测了下没问题

![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/114645197/32996da8-228f-48ef-b542-3828424c5d4d)

**Comment by Shapaper233** [comment]
可以可以了，之前docker配置忘记做持久化了，刚才忘记给环境变量了（）

**Comment by pk5ls20** [comment]
> 请问支持右键图片直接上传嘛，个人理解是不是可以复用那个右键的逻辑，按下后直接丢上传列表并弹个气泡提示，表明正在上传😚

https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/releases/tag/v0.1.0 可以了
