### ISSUE TITLE
BUG：Linux下无法正常使用

### ISSUE THREAD

**Issue by Shapaper233** [pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch#8]
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/157946924/2237c57c-d8f8-4fda-9a92-0631b683673b)

似乎每次搜索或者投🎲都会多一个界面不销毁
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/157946924/01e2f827-c39f-4161-acb4-a9ce108a99b8)

图片也无法显示（只有图片的名字）
并且右键搜索有概率不生效{似乎右键表情第二次才可以显示，第一次按不触发}

```
       _,met$$$$$gg.          shapaper@Debian 
    ,g$$$$$$$$$$$$$$$P.       --------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: 81FW Lenovo Legion Y7000 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-21-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 14 hours, 40 mins 
 $$P      d$'     ,    $$P    Packages: 2723 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: Plasma 5.27.5 
 `$$b      "-.__              WM: kwin 
  `Y$$                        Theme: [Plasma], Breeze [GTK2/3] 
   `Y$$.                      Icons: Fluent-orange-light [Plasma], Fluent-orange-light [GTK2/3] 
     `$$b.                    Terminal: konsole 
       `Y$$b.                 CPU: Intel i7-8750H (12) @ 4.100GHz 
          `"Y$b._             GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
              `"""            GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
                              Memory: 13957MiB / 23904MiB 
```
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/157946924/6fef8a21-52a9-4411-8445-d96531e00dad)
![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/157946924/0249e5f7-5abb-440f-9947-192e29baf2e5)

**Comment by pk5ls20** [comment]
无法复现，尝试重新安装插件下？
要是方便的话提供下加载插件的完整列表
----
复现环境如下：

![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/114645197/bc255a53-eb34-4c57-b4ee-9a3d34a2f883)

![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/114645197/22f3bb24-cc05-4dfa-9558-38e141251234)


![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/114645197/5486ae29-d446-40ad-90b4-cdbd677820b2)

**Comment by Shapaper233** [comment]
似乎是release包的bug,这个构建正常使用，推荐更新下release

**Comment by Shapaper233** [comment]
搜索bug仍然出现

**Comment by Shapaper233** [comment]
我猜是wayland鼠标捕获的问题？可能要根据平台做不同的策略吧

**Comment by pk5ls20** [comment]
> 似乎是release包的bug,这个构建正常使用，推荐更新下release

好

**Comment by pk5ls20** [comment]
> 我猜是wayland鼠标捕获的问题？可能要根据平台做不同的策略吧

怪，我就是在wayland下测的，右键搜索表现正常

![image](https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/assets/114645197/36c71048-3bac-4cc1-8011-0a3928bf4cc0)

**Comment by pk5ls20** [comment]
> 我猜是wayland鼠标捕获的问题？可能要根据平台做不同的策略吧

刚才试了下，在Wayland和X11下都有这个问题

**Comment by pk5ls20** [comment]
@Shapaper233 试一下这个构建版右键菜单是否正常 -> https://github.com/pk5ls20/LiteLoaderQQNT-NekoImageGallerySearch/actions/runs/9468595002
